# **Indian Road Accident Analysis**

## **Objective**
Prepare the road accident dataset for analysis by validating data quality,
checking data types, creating analytical features, and exporting a cleaned dataset.


# **Dataset**

Rows : 20000

Columns : 24

## **Tools Used**
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Plotly

# **Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Load Dataset**

In [ ]:
df = pd.read_csv('/content/indian_roads_dataset.csv')

# **Preview Dataset**

In [ ]:
df.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10

In [ ]:
df.tail()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
19995,19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,3:00,3,Thursday,0,...,high,31,low,distraction,minor,3,2,0,NaN,0.10
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,1:00,1,Saturday,1,...,high,20,low,distraction,major,4,2,0,NaN,0.10
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15:00,15,Saturday,1,...,high,22,low,weather,minor,3,3,0,NaN,0.10
19998,19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,4:00,4,Sunday,1,...,high,33,low,poor road,minor,1,0,0,NaN,0.10
19999,19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23:00,23,Friday,0,...,low,39,high,overspeeding,minor,4,2,0,NaN,0.65

In [ ]:
df.sample(5)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
13697,13697,Pune,Maharashtra,18.507863,73.836349,2025-03-20,17:00,17,Thursday,0,...,high,19,low,overspeeding,minor,1,0,1,NaN,0.25
7506,7506,Kolkata,West Bengal,22.486222,88.337665,2025-03-14,5:00,5,Friday,0,...,high,37,medium,weather,major,3,0,0,NaN,0.10
4868,4868,Bangalore,Karnataka,13.128269,77.535248,2024-12-09,5:00,5,Monday,0,...,high,36,high,drunk driving,minor,2,0,0,NaN,0.30
1001,1001,Chennai,Tamil Nadu,13.105252,80.289928,2023-06-28,21:00,21,Wednesday,0,...,high,23,medium,weather,fatal,3,3,0,NaN,0.30
4674,4674,Chennai,Tamil Nadu,13.020792,80.288117,2024-04-25,19:00,19,Thursday,0,...,high,28,high,drunk driving,minor,5,1,1,NaN,0.45

# **Dataset Shape**

In [ ]:
df.shape # The dataset contains 20000 rows and 24 columns.

(20000, 24)

# **Dataset Information**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  object
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           115 non-null    object
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), object(12)
memory usage: 3.7+ MB

# **Column Names**

In [ ]:
df.columns

Index(['accident_id', 'city', 'state', 'latitude', 'longitude', 'date', 'time',
       'hour', 'day_of_week', 'is_weekend', 'road_type', 'lanes',
       'traffic_signal', 'weather', 'visibility', 'temperature',
       'traffic_density', 'cause', 'accident_severity', 'vehicles_involved',
       'casualties', 'is_peak_hour', 'festival', 'risk_score'],
      dtype='object')

# **Check Missing Values**

In [ ]:
df.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

**Percentage**

In [ ]:
((df.isnull().sum()/len(df))*100).round(2)

accident_id           0.00
city                  0.00
state                 0.00
latitude              0.00
longitude             0.00
date                  0.00
time                  0.00
hour                  0.00
day_of_week           0.00
is_weekend            0.00
road_type             0.00
lanes                 0.00
traffic_signal        0.00
weather               0.00
visibility            0.00
temperature           0.00
traffic_density       0.00
cause                 0.00
accident_severity     0.00
vehicles_involved     0.00
casualties            0.00
is_peak_hour          0.00
festival             99.42
risk_score            0.00
dtype: float64

# **Handle Missing Values**

In [ ]:
df['festival'].unique()

array([nan, 'Holi', 'Diwali', 'Eid', 'New Year'], dtype=object)

In [ ]:
df['festival'] =  df['festival'].fillna('No Festival') # fill Nan value by 'No Festival'

In [ ]:
df['festival'].unique()

array(['No Festival', 'Holi', 'Diwali', 'Eid', 'New Year'], dtype=object)

In [ ]:
df.isnull().sum()

accident_id          0
city                 0
state                0
latitude             0
longitude            0
date                 0
time                 0
hour                 0
day_of_week          0
is_weekend           0
road_type            0
lanes                0
traffic_signal       0
weather              0
visibility           0
temperature          0
traffic_density      0
cause                0
accident_severity    0
vehicles_involved    0
casualties           0
is_peak_hour         0
festival             0
risk_score           0
dtype: int64

# **Duplicate Values**

In [ ]:
df.duplicated().sum() # No Duplicate Value

np.int64(0)

# **Check Unique Values**

In [ ]:
df.nunique()

accident_id          20000
city                     8
state                    7
latitude             19907
longitude            19927
date                  1201
time                    24
hour                    24
day_of_week              7
is_weekend               2
road_type                3
lanes                    6
traffic_signal           2
weather                  3
visibility               3
temperature             26
traffic_density          3
cause                    5
accident_severity        3
vehicles_involved        5
casualties               6
is_peak_hour             2
festival                 5
risk_score              18
dtype: int64

# **Data Type Validation & correction**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  object
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           20000 non-null  object
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), object(12)
memory usage: 3.7+ MB

In [ ]:
df['accident_id'] = df['accident_id'].astype(np.int16)
df['latitude'] = df['latitude'].astype(np.float32)
df['longitude'] = df['longitude'].astype(np.float32)
df['hour'] = df['hour'].astype(np.int8)
df['is_weekend'] = df['is_weekend'].astype(np.int8)
df['lanes'] = df['lanes'].astype(np.int8)
df['traffic_signal'] = df['traffic_signal'].astype(np.int8)
df['temperature'] = df['temperature'].astype(np.int8)
df['vehicles_involved'] = df['vehicles_involved'].astype(np.int8)
df['is_peak_hour'] = df['is_peak_hour'].astype(np.int8)
df['risk_score'] = df['risk_score'].astype(np.float32)
df['date'] = pd.to_datetime(df['date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int16
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float32
 4   longitude          20000 non-null  float32
 5   date               20000 non-null  datetime64[ns]
 6   time               20000 non-null  object
 7   hour               20000 non-null  int8
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int8
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int8
 12  traffic_signal     20000 non-null  int8
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int8
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int8
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int8
 22  festival           20000 non-null  object
 23  risk_score         20000 non-null  float32
dtypes: datetime64[ns](1), float32(3), int16(1), int64(1), int8(7), object(11)
memory usage: 2.4+ MB

# **Feature Engineering**

1. **Severity Index**

In [ ]:
df['severity_index'] = (
    df['vehicles_involved'] *
    df['casualties']
)

2. **Risk Quartile**

In [ ]:
df['risk_quartile'] = pd.qcut(
    df['risk_score'],
    q=4,
    labels=['Q1', 'Q2', 'Q3', 'Q4']
)

3. **Weekend Label Change**

In [ ]:
df['is_weekend'] = df['is_weekend'].replace({
    0:'Weekday',
    1:'Weekend'
})

4. **Peak Hour Label**

In [ ]:
df['is_peak_hour'] = df['is_peak_hour'].replace({
    0:'Non Peak Hour',
    1:'Peak Hour'
})

# **Validation Check**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int16
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float32
 4   longitude          20000 non-null  float32
 5   date               20000 non-null  datetime64[ns]
 6   time               20000 non-null  object
 7   hour               20000 non-null  int8
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  object
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int8
 12  traffic_signal     20000 non-null  int8
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int8
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int8
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  object
 22  festival           20000 non-null  object
 23  risk_score         20000 non-null  float32
 24  severity_index     20000 non-null  int64
 25  risk_quartile      20000 non-null  category
dtypes: category(1), datetime64[ns](1), float32(3), int16(1), int64(2), int8(5), object(13)
memory usage: 2.8+ MB

In [ ]:
df.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score,severity_index,risk_quartile
0,0,Pune,Maharashtra,18.680826,73.930389,2023-10-22,5:00,5,Sunday,Weekend,...,high,weather,fatal,2,2,Non Peak Hour,No Festival,0.85,4,Q4
1,1,Mumbai,Maharashtra,18.817732,72.790848,2023-05-21,4:00,4,Sunday,Weekend,...,low,weather,major,4,3,Non Peak Hour,No Festival,0.10,12,Q1
2,2,Mumbai,Maharashtra,19.096889,72.819427,2024-07-10,13:00,13,Wednesday,Weekday,...,medium,weather,minor,1,1,Non Peak Hour,No Festival,0.45,1,Q2
3,3,Chandigarh,Punjab,30.787806,76.847504,2025-03-30,11:00,11,Sunday,Weekend,...,high,distraction,minor,5,2,Non Peak Hour,No Festival,0.65,10,Q4
4,4,Chennai,Tamil Nadu,12.965155,80.283310,2024-01-25,16:00,16,Thursday,Weekday,...,low,distraction,minor,2,1,Non Peak Hour,No Festival,0.10,2,Q1

# **Save Dataset**

In [ ]:
df.to_csv(
    "cleaned_road_accident.csv",
    index=False
)